/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Database.conectorDB;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class inicioSeccion extends javax.swing.JFrame {

    private String gia = "";

    /**
     * Creates new form inicioSeccion
     */
    public inicioSeccion() {
        initComponents();
        this.setLocationRelativeTo(null);

        ImageIcon img = new ImageIcon(ClassLoader.getSystemResource("images/ventas_ico.png"));

        Image imagen = img.getImage();
        this.setIconImage(imagen);
        ImageIcon imagenEscalado = new ImageIcon(imagen.getScaledInstance(lblFotoEmpresa.getWidth(), lblFotoEmpresa.getHeight(), Image.SCALE_SMOOTH));
        lblFotoEmpresa.setIcon(imagenEscalado);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFotoEmpresa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_inicioseccion = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(93, 141, 132));

        jPanel1.setBackground(new java.awt.Color(93, 141, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("EMPRESA-X");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 219, -1));
        jPanel1.add(lblFotoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 152, 104));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CODIGO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, -1));

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtUser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtUserComponentShown(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtUserPropertyChange(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 195, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 195, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 130, -1));

        btn_inicioseccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_inicioseccion.setText("INICIAR SECCION");
        btn_inicioseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioseccionActionPerformed(evt);
            }
        });
        btn_inicioseccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_inicioseccionKeyPressed(evt);
            }
        });
        jPanel1.add(btn_inicioseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 190, -1));

        lblInfo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 843, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      private void iniciarseccion() {
        String cod = txtUser.getText();
        conectorDB con = new conectorDB();
        try {
            PreparedStatement ps = con.concectar().prepareStatement("SELECT CODIGO,NOMBRE,DESCCRIPCION FROM VENDEDOR,PERSONA,CATEGORIAVENDEDOR WHERE IDCATEGORIAVENDEDOR=ID AND CI=CIPERSONA AND CODIGO=?");
            ps.setString(1, cod);
            ResultSet respuesta = ps.executeQuery();

            if (respuesta != null && respuesta.next()) {
                System.out.println(respuesta.getString("CODIGO"));
                if (cod.compareTo(respuesta.getString("CODIGO")) == 0) {

                    Index ini = new Index(true, respuesta.getString("NOMBRE") + " - " + respuesta.getString("DESCCRIPCION"));

                    this.dispose();

                    lblInfo.setText("");
                } else {
                    lblInfo.setText("Usuario incorrecto!");
                    lblInfo.setForeground(Color.red);
                }
            } else {
                lblInfo.setText("Usuario incorrecto!");
                lblInfo.setForeground(Color.red);
            }
            ps.close();

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btn_inicioseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioseccionActionPerformed
        iniciarseccion();
    }//GEN-LAST:event_btn_inicioseccionActionPerformed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txtPassword.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                txtPassword.requestFocus();
                break;
            default:

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                btn_inicioseccion.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtUser.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                btn_inicioseccion.requestFocus();
                break;
            default:
// TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordKeyPressed
    }
    private void btn_inicioseccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_inicioseccionKeyPressed

        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                iniciarseccion();
                break;
            case KeyEvent.VK_UP:
                txtPassword.requestFocus();
                break;
            default:

        } // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioseccionKeyPressed

    private void txtUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtUserPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPropertyChange

    private void txtUserComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtUserComponentShown
        System.out.println(evt.getComponent().getFocusListeners());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserComponentShown


    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        gia += evt.getKeyChar();
        System.out.println(gia);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioSeccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicioseccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFotoEmpresa;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
